[lucidboard]

"LucidboardWeb.Endpoint".http.port = 8080
"LucidboardWeb.Endpoint".url.port = 8080
"LucidboardWeb.Endpoint".url.host = "localhost"

"Lucidboard.Repo".hostname = "${PG_HOST | default: db}"
"Lucidboard.Repo".port = "${PG_PORT | default: 5432}"
"Lucidboard.Repo".password = "${PG_PASS | default: verysecure123}"
